name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint_and_test:
    name: Linting and Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_PIPELINEWISE_SA }}
          export_default_credentials: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup virtual environment
        run: make venv

      - name: Pylinting
        run: make pylint

      - name: Unit Tests
        run: make unit_test

      - name: Integration Tests
        env:
          LOGGING_CONF_FILE: ./sample_logging.conf
          TARGET_BIGQUERY_PROJECT: ${{ secrets.TARGET_BIGQUERY_PROJECT }}
          TARGET_BIGQUERY_SCHEMA: ${{ secrets.TARGET_BIGQUERY_SCHEMA }}
          TARGET_BIGQUERY_LOCATION: ${{ secrets.TARGET_BIGQUERY_LOCATION }}
        run: make integration_test
